import { createServerFn } from "@tanstack/react-start";
import Replicate from "replicate";

const ROOM_STYLE_PROMPTS: Record<string, Record<string, string>> = {
  kitchen: {
    coastal: "Transform this room into a modern coastal-style kitchen. Use a light, airy palette of soft whites, warm beige, and muted ocean blues. Replace cabinetry with white or light wood finishes, paired with marble or quartz countertops and a clean white or pale blue backsplash. Add natural textures such as wicker or rattan bar stools and open wooden shelving with ceramic dishware. Ensure the space feels bright, fresh, and uncluttered with plenty of natural light. Maintain a functional kitchen layout with subtle coastal decor, avoiding overly themed elements. Photorealistic, soft daylight, high detail.",
    modernluxury: "A modern luxury kitchen with a sleek, high-end design and minimalist layout. Features include custom handleless cabinetry in matte finishes (soft white, taupe, or charcoal), a large waterfall island with polished marble or quartz countertop, and integrated high-end appliances seamlessly built into the cabinetry. The backsplash is a full-height stone slab or subtle textured tile. Lighting includes pendant lights above the island with warm ambient glow and under-cabinet LED strips. The space is clean and uncluttered, with metallic accents in brushed brass or matte black. Flooring is polished stone or wide-plank hardwood. Large windows provide natural light, enhancing a refined, elegant, and functional atmosphere. Photorealistic, balanced lighting, ultra-detailed.",
    japandi: "Transform this kitchen into a Japandi-style space. Use flat-panel light wood cabinetry with clean lines and integrated handles. Apply a neutral palette of warm white, beige, and soft grey with natural stone or concrete countertops. Add open wooden shelving with minimal ceramic dishware. Incorporate matte black or brushed metal fixtures for subtle contrast. Include natural textures like wood grain and linen. Keep surfaces uncluttered and functional. Use soft natural daylight and warm ambient lighting for a calm, balanced atmosphere.",
    scandinavian: "Transform this kitchen into a Scandinavian interior design style. Use a bright, clean aesthetic with white or soft neutral cabinetry paired with light wood elements such as oak or birch countertops or open shelving. Emphasize minimalism with flat-panel cabinets, hidden handles, and uncluttered surfaces. Incorporate natural textures like wood and subtle matte finishes. Add soft, diffused natural lighting with sheer window treatments. Include minimal decor such as a few ceramic pieces, glass jars, and small green plants or herbs. Keep the space functional, airy, and highly organized. Avoid bold colors, excessive decoration, or heavy materials. Maintain a calm, modern Nordic atmosphere.",
    modernfarmhouse: "A bright modern farmhouse kitchen with a neutral palette of warm whites, soft grays, and natural wood tones. White shaker cabinets with matte black hardware contrast with a light wood or butcher-block island countertop. A farmhouse apron-front sink sits beneath a large window, bringing in abundant natural light. The backsplash features white subway tile or shiplap paneling for subtle texture. Open wooden shelving displays simple ceramic dishware and glass jars. Lighting includes black metal pendant lights or industrial farmhouse fixtures above the island. The flooring is wide-plank light oak or weathered wood. Decor is minimal: a few potted herbs, a wooden cutting board, and neutral textiles. The overall look is clean, airy, rustic yet refined, with a cozy and functional atmosphere.",
    urbanmasculine: "Transform this kitchen into an Urban Masculine (Modern Industrial Luxe) design. Use a dark, moody palette with matte black cabinetry, charcoal tones, and deep wood finishes. Incorporate industrial materials such as concrete surfaces, exposed brick or concrete walls, and blackened steel details. Add a statement kitchen island with a dark marble or stone countertop and waterfall edges. Use sleek, handleless cabinets or minimalist hardware in brushed metal or matte black. Include industrial-style pendant lighting with black metal or smoked glass shades over the island. Integrate subtle warm LED strip lighting under cabinets for contrast. Add bar stools with leather or wood finishes and metal frames. Keep decor minimal. Ensure a balance between raw industrial textures and refined luxury finishes. Photorealistic, cinematic lighting, high detail, realistic materials, 4k.",
    biophilic: "Transform this kitchen into a biophilic interior design style. Incorporate natural wood cabinetry, stone or marble countertops, and woven textures like rattan or bamboo. Add abundant greenery such as hanging herbs, potted plants on shelves, and window-side plants. Use a warm earthy palette with greens, beige, and wood tones. Enhance natural lighting with sunlight streaming through windows, creating a fresh and airy atmosphere. Replace artificial materials with organic finishes and introduce subtle nature-inspired decor. The space should feel like a healthy, nature-connected kitchen garden.",
    maximalist: "Transform this kitchen into a maximalist interior design style. Introduce bold, colorful cabinetry in jewel tones like emerald green, navy blue, or deep burgundy. Add patterned backsplash tiles and possibly wallpaper with floral or geometric motifs. Style open shelving with an abundant display of dishes, glassware, cookbooks, and decorative objects. Incorporate layered textures such as patterned rugs, brass or gold hardware, marble or wood surfaces, and mixed materials. Add hanging pots, statement lighting fixtures, and plants for vibrancy. Ensure the space feels rich, eclectic, and curated, with a balance of color repetition and visual harmony while maintaining functionality.",
  },
  livingroom: {
    coastal: "Transform this room into a modern coastal living room. Use soft whites, sandy neutrals, and muted blue accents. Replace furniture with a comfortable linen slipcovered sofa, light wood coffee table, and woven textures like jute rugs and rattan chairs. Add soft textiles such as cushions and throws, and keep the layout open and relaxed. Decor should be minimal with subtle coastal touches like glass vases or ocean-inspired artwork. Bright, airy, uncluttered, photorealistic, natural lighting.",
    modernluxury: "A modern luxury living room with an open, airy layout and sophisticated design. Features a low-profile plush sofa, designer armchairs, and a statement coffee table in marble or glass. Neutral tones dominate (cream, beige, soft gray) with darker accents. A feature wall may include textured panels or a minimalist fireplace. Lighting is layered with a sculptural chandelier, recessed lighting, and warm LED accents. A large area rug adds softness, and curated decor like abstract art and metallic accessories enhance elegance. The space feels calm, refined, and upscale. Highly realistic, cinematic lighting.",
    japandi: "Transform this living room into a Japandi-style interior. Use a low-profile sofa in neutral fabric (linen or cotton), paired with a simple wooden coffee table. Keep a restrained palette of beige, taupe, soft grey, and natural wood. Add a few curated decor items like a ceramic vase or a small indoor plant. Include soft textiles for warmth but avoid clutter. Use diffused lighting and emphasize open, breathable space with a calm, cozy, minimalist feel.",
    scandinavian: "Transform this living room into a Scandinavian interior design style. Use a soft neutral color palette with whites, light grays, and warm beige tones. Include a simple, low-profile sofa with clean lines, paired with light wood furniture such as a coffee table or side tables. Layer cozy textures like wool throws, linen cushions, and soft rugs to create a warm hygge atmosphere. Add warm ambient lighting using floor lamps or pendant lights. Keep decor minimal with a few framed artworks, ceramic objects, and indoor plants. Ensure the space feels open, uncluttered, and calm, with a strong sense of natural light and balance.",
    modernfarmhouse: "A cozy modern farmhouse living room featuring a neutral color palette of whites, creams, and soft grays. A large linen-upholstered sofa with plush cushions is paired with a reclaimed wood coffee table. The walls are painted matte white or finished with shiplap paneling. Exposed wooden ceiling beams add warmth and character. A fireplace with a simple wood mantel serves as a focal point, decorated with minimal accessories. Black metal accents appear in lighting fixtures and decor details. Layered textiles such as knit throws and soft rugs create comfort. The atmosphere is airy, inviting, and relaxed.",
    urbanmasculine: "Transform this living room into an Urban Masculine (Modern Industrial Luxe) style. Use a dark neutral palette with charcoal, matte black, deep browns, and warm taupe accents. Replace furniture with a low-profile leather sofa in dark brown or black, paired with a solid wood or metal coffee table. Use structured, masculine silhouettes with clean lines. Add textures such as exposed concrete or brick walls, dark wood panels, and metal accents. Include a large textured area rug in neutral tones. Incorporate layered lighting: industrial floor lamps, black metal fixtures, and warm ambient lighting for contrast. Keep decor minimal and curated—abstract monochrome artwork, metal sculptures, and a few books or objects. Photorealistic, cinematic lighting, high detail, 4k.",
    biophilic: "Transform this living room into a biophilic interior design style. Introduce large indoor plants, layered greenery, and possibly a vertical plant wall. Use natural materials like wood furniture, linen upholstery, and woven textiles. Apply a soft earthy color palette with greens, warm neutrals, and organic textures. Incorporate curved furniture and organic shapes. The atmosphere should feel calm, relaxing, and connected to nature, like an indoor oasis.",
    maximalist: "Transform this living room into a maximalist interior design style. Add a bold statement sofa in velvet or richly textured fabric in jewel tones. Layer multiple patterned rugs, cushions, and throws. Create a gallery wall filled with diverse artwork, mirrors, and frames. Incorporate bookshelves filled with books and decorative objects, indoor plants, sculptural decor, and statement lighting such as chandeliers or artistic lamps. Mix vintage and modern furniture pieces with contrasting patterns and textures. Ensure the room feels vibrant, layered, and expressive while maintaining a cohesive color palette and intentional composition.",
  },
  diningroom: {
    coastal: "Transform this room into a coastal-style dining room with a light wood dining table and simple, elegant chairs, possibly with woven or linen textures. Use a neutral palette of whites, beige, and soft blues. Incorporate natural materials such as rattan lighting fixtures and a jute rug. Keep the space clean, open, and inviting with minimal decor like ceramic tableware or subtle coastal centerpieces. Emphasize natural light and a relaxed, beach-house atmosphere. Photorealistic, balanced composition.",
    modernluxury: "A modern luxury dining room centered around a statement dining table made of marble, glass, or dark wood, surrounded by upholstered high-end chairs. The design is clean and symmetrical, with a neutral palette and subtle contrast. Above the table hangs a striking chandelier or linear pendant light creating a focal point. Walls may feature elegant paneling or large-scale artwork. Flooring is polished stone or hardwood with a soft area rug beneath the table. Minimal decor includes sculptural centerpieces and metallic accents. The atmosphere is intimate, elegant, and refined. Photorealistic, warm ambient lighting.",
    japandi: "Transform this dining room into a Japandi-style setting. Feature a solid wood dining table with simple, clean lines and minimal chairs. Use a muted earthy palette and natural materials. Add a single statement pendant light in paper or matte finish. Keep table decor minimal—ceramic plates, a small vase, or linen runner. Maintain symmetry, simplicity, and a calm, uncluttered environment.",
    scandinavian: "Transform this dining room into a Scandinavian interior design style. Feature a light wood dining table with simple, clean-lined chairs. Use a neutral color palette with white walls and soft natural tones. Add a minimalist pendant light centered above the table. Keep decor subtle with a simple centerpiece such as a ceramic vase or greenery. Emphasize openness, natural light, and functional simplicity. Avoid clutter, bold colors, or heavy furniture. Maintain a calm, elegant Nordic dining atmosphere.",
    modernfarmhouse: "A modern farmhouse dining room centered around a large reclaimed wood dining table with visible grain and texture. Seating includes a mix of wooden chairs and a bench for a casual, welcoming feel. The space uses a neutral palette with white or shiplap walls and soft natural tones. A statement chandelier with black metal or aged iron hangs above the table. Decor is simple: a linen table runner, ceramic vases, and greenery such as eucalyptus. The flooring is light wood, and natural light enhances the warm, rustic yet clean aesthetic.",
    urbanmasculine: "Transform this dining room into an Urban Masculine (Modern Industrial Luxe) design. Use a dark, refined palette with charcoal, black, and deep wood tones. Feature a large solid wood or dark stone dining table with bold presence. Pair with leather or upholstered chairs in dark tones with metal or wood frames. Add a statement lighting fixture above the table—industrial chandelier or linear pendant in black metal or brushed brass. Incorporate textures like concrete or brick walls, dark paneling, and subtle metallic accents. Use minimal table decor such as ceramic pieces or glassware. Maintain a clean, structured layout with strong symmetry and a sophisticated, masculine atmosphere. Photorealistic, cinematic lighting, 4k.",
    biophilic: "Transform this dining room into a biophilic interior design style. Feature a natural wood dining table with organic textures and neutral-toned seating. Add greenery such as a plant centerpiece, hanging plants, or surrounding plant clusters. Use warm earthy tones and natural materials like linen, wood, and stone. Enhance the space with soft natural light and an open, airy feel. The setting should feel inviting, grounded, and inspired by nature.",
    maximalist: "Transform this dining room into a maximalist interior design style. Add bold wallpaper with intricate patterns or rich colors. Use a statement dining table paired with mismatched or upholstered chairs in vibrant fabrics. Incorporate a dramatic chandelier or pendant lighting as a focal point. Style the table with layered place settings, colorful glassware, and decorative centerpieces. Add artwork, mirrors, and shelves with curated objects around the room. Ensure the space feels luxurious, layered, and visually rich with a balance of bold patterns and cohesive tones.",
  },
  bedroom: {
    coastal: "Transform this room into a serene coastal-style primary bedroom. Use soft whites, warm neutrals, and muted blue tones. Feature a light wood or upholstered bed with layered linen bedding and soft textures. Add minimal furniture with clean lines, such as wooden bedside tables and soft lighting. Use sheer curtains for natural light and keep decor subtle with calming coastal elements. The space should feel peaceful, airy, and elegant. Photorealistic, soft natural light.",
    modernluxury: "A modern luxury bedroom with a serene and sophisticated atmosphere. A large upholstered bed with a tall headboard acts as the focal point, dressed in high-quality linens in neutral tones. Nightstands with designer lamps flank the bed. The room includes soft textures like plush rugs, velvet cushions, and layered bedding. Lighting is warm and ambient with recessed lights and subtle LED accents. Walls are minimal with paneling or soft textures, complemented by elegant artwork. Large windows with sheer curtains allow natural light. The overall mood is calm, spacious, and upscale. Ultra-realistic, soft lighting.",
    japandi: "Transform this bedroom into a Japandi-style retreat. Use a low wooden bed frame with neutral linen bedding. Keep colors soft—warm white, beige, and muted grey. Add minimal furniture such as a simple bedside table and soft lighting with paper or fabric lamps. Include natural textures and a small plant. Keep the space uncluttered, serene, and restful with soft diffused lighting.",
    scandinavian: "Transform this bedroom into a Scandinavian interior design style. Use a calming palette of whites, soft grays, and warm neutrals. Include a simple bed with light wood framing and layered bedding in linen or cotton. Add soft textures such as throws, cushions, and a subtle rug. Use warm ambient lighting with bedside lamps or pendant lights. Keep decor minimal with simple artwork and a few natural elements like plants. Ensure the space feels calm, cozy, uncluttered, and restful.",
    modernfarmhouse: "A serene modern farmhouse bedroom with soft neutral tones, including warm whites, beige, and light gray. The bed features a wooden or upholstered headboard with layered linen bedding, textured blankets, and soft pillows. Walls are matte white or shiplap, and furniture is light wood with simple lines. Bedside tables hold minimal decor like ceramic lamps and small plants. Natural light flows through sheer curtains, creating a calm and airy ambiance. The space feels cozy, uncluttered, and restful.",
    urbanmasculine: "Transform this bedroom into an Urban Masculine (Modern Industrial Luxe) style. Use a moody, dark palette with charcoal, black, and warm wood tones. Feature a low-profile bed with a leather or upholstered headboard in dark tones. Add layered bedding in neutral shades with subtle texture. Incorporate materials like concrete walls, dark wood panels, and metal accents. Add minimal bedside tables in wood or metal. Use soft, warm lighting with industrial-style wall sconces or pendant lights. Keep decor minimal—abstract art, books, and a few curated accessories. Create a calm, refined, masculine atmosphere. Photorealistic, cinematic lighting, 4k.",
    biophilic: "Transform this bedroom into a biophilic interior design style. Use soft natural fabrics like linen bedding, wooden furniture, and warm neutral tones. Add calming greenery such as bedside plants, hanging plants, or a small indoor garden corner. Emphasize natural light, soft shadows, and an airy layout. Incorporate organic shapes and minimal clutter. The atmosphere should feel peaceful, restorative, and deeply connected to nature.",
    maximalist: "Transform this bedroom into a maximalist interior design style. Add a statement bed with a bold headboard in velvet or patterned fabric. Layer bedding with multiple textures, patterns, and colors such as jewel tones and rich neutrals. Incorporate wallpaper or a feature wall, layered rugs, and abundant cushions and throws. Add bedside tables with decorative lamps, books, and curated objects. Include a gallery wall or bold artwork, plants, and mixed materials like wood, metal, and glass. Ensure the space feels cozy, dramatic, and richly detailed while remaining visually balanced.",
  },
  kidsroom: {
    coastal: "Transform this room into a coastal-style kids bedroom. Use soft, playful tones like light blue, sandy beige, and white. Include simple, child-friendly furniture in light wood with soft textiles. Add subtle coastal-themed elements like ocean-inspired artwork or patterns, while keeping the design clean and not overly themed. Ensure the space feels bright, cheerful, and organized with natural light. Photorealistic, soft and airy.",
    modernluxury: "A modern luxury kids room blending playful elements with a refined aesthetic. Features a comfortable bed with soft, high-quality bedding in light neutral tones with subtle pastel accents. Furniture is modern and safe, with rounded edges and premium materials. Storage is integrated and minimal. Decorative elements include soft toys, playful artwork, and a cozy rug while maintaining a clean, uncluttered look. Lighting is warm and gentle, creating a calm environment. The space feels stylish yet child-friendly. Photorealistic, soft lighting.",
    japandi: "Transform this kids room into a Japandi-style space. Use soft neutral tones with subtle warm accents. Incorporate natural wood furniture and simple, safe shapes. Add soft textiles and minimal toys made of natural materials. Keep the space playful yet calm, avoiding bright colors or clutter. Maintain a cozy, serene atmosphere with soft lighting.",
    scandinavian: "Transform this kids room into a Scandinavian interior design style. Use a soft, neutral base palette with whites and light grays, accented by gentle pastel tones. Incorporate light wood furniture with simple shapes and rounded edges. Add cozy textiles and natural materials. Include minimal, thoughtfully selected toys and decor, focusing on wooden toys and simple shapes. Keep the space playful yet calm, uncluttered, and functional. Maintain a clean, safe, and warm Nordic atmosphere.",
    modernfarmhouse: "A modern farmhouse kids room with a soft, neutral base and gentle pastel accents. Light wood furniture, woven baskets, and cotton or linen textiles create a warm and natural environment. The walls are white or lightly textured, with simple wall decor like framed prints or wooden accents. The space includes cozy rugs, soft bedding, and minimal clutter. Toys are styled neatly in open baskets or shelves. The atmosphere is calm, playful, and inviting, blending farmhouse warmth with child-friendly softness.",
    urbanmasculine: "Transform this kids room into a softened Urban Masculine (Modern Industrial Luxe) style. Use a muted neutral palette with warm grays, soft browns, and subtle black accents while keeping the space inviting. Incorporate natural wood furniture with simple, clean lines. Add soft textiles like rugs, cushions, and bedding to balance the industrial elements. Use subtle industrial features such as metal accents or simple black lighting fixtures, but avoid overly dark or heavy finishes. Include playful yet minimal decor—simple wall art, books, and functional storage. Keep the space open, warm, and comfortable. Photorealistic, cinematic lighting, 4k.",
    biophilic: "Transform this kids room into a biophilic interior design style. Use safe, natural materials like light wood furniture, cotton fabrics, and soft textures. Add playful greenery (child-safe plants), nature-themed decor, and soft earthy colors like pastel greens and warm neutrals. Incorporate organic shapes and a cozy, imaginative environment. The space should feel playful, calming, and inspired by nature.",
    maximalist: "Transform this kids room into a maximalist interior design style. Use bright, playful colors and mix bold patterns such as stripes, polka dots, and whimsical prints. Add colorful bedding, layered rugs, and plenty of cushions. Incorporate shelves filled with toys, books, and decorative items. Create a fun gallery wall with playful artwork and illustrations. Add creative lighting and interactive decor elements. Ensure the space feels energetic, imaginative, and layered while still organized and visually cohesive.",
  },
  playroom: {
    coastal: "Transform this room into a coastal-style playroom. Use a light, bright palette of whites, soft blues, and sandy tones. Include functional storage in light wood, woven baskets, and soft rugs. Keep the space open, fun, and uncluttered while maintaining a calm coastal aesthetic. Add subtle playful decor with minimal coastal references. Ensure plenty of natural light and a welcoming atmosphere. Photorealistic, high detail.",
    modernluxury: "A modern luxury playroom designed to be fun yet elegant. Features built-in storage units, open shelving, and designated play zones. The color palette remains soft and neutral with muted playful accents. Includes soft rugs, comfortable seating, and interactive elements while maintaining a clean and organized layout. Lighting is bright but warm, with natural light from large windows. Materials are high-quality and durable. The space feels inviting, creative, and sophisticated. Ultra-detailed, realistic.",
    japandi: "Transform this playroom into a Japandi-style space. Use neutral tones and natural materials like wood and woven baskets for toy storage. Keep the layout open and organized with minimal visual clutter. Include soft textures and simple, functional furniture. Maintain a calm, balanced environment that encourages creativity without overstimulation.",
    scandinavian: "Transform this playroom into a Scandinavian interior design style. Use a bright, neutral base with soft whites and natural wood tones. Include simple storage solutions such as open shelving and baskets to keep the space organized. Add minimal, well-designed toys made from natural materials. Incorporate soft rugs and cushions for comfort. Keep the space clean, functional, and uncluttered while maintaining a light, playful atmosphere.",
    modernfarmhouse: "A modern farmhouse playroom designed with simplicity and warmth. The color palette is neutral with whites, beige, and soft earthy tones. Wooden toys, open shelving, and woven storage baskets keep the space organized and visually clean. A soft area rug provides a comfortable play surface, and natural light fills the room. Decor is minimal, with a few playful elements that still match the farmhouse aesthetic. The overall feel is cozy, uncluttered, and functional, encouraging creativity while maintaining visual calm.",
    urbanmasculine: "Transform this playroom into a modern Urban Masculine (Modern Industrial Luxe) inspired space adapted for children. Use a neutral palette with warm grays, wood tones, and soft contrast. Incorporate functional storage with wood and metal shelving. Add durable materials like wood flooring and soft rugs for comfort. Use minimal industrial elements such as simple black lighting fixtures and subtle metal accents. Keep the design clean and organized. Add playful elements in a restrained way—books, toys, and textures without clutter. Ensure the space feels open, safe, and visually calm. Photorealistic, 4k.",
    biophilic: "Transform this playroom into a biophilic interior design style. Include natural materials like wood play structures, soft cotton mats, and woven textures. Add greenery throughout the space while keeping it open and safe. Use soft earthy tones with playful accents inspired by nature. Incorporate organic shapes and maximize natural light. The space should feel energetic yet calming, like an indoor natural playground.",
    maximalist: "Transform this playroom into a maximalist interior design style. Fill the space with bold colors, layered patterns, and creative zones for play and learning. Add vibrant rugs, wall art, and playful wallpaper. Incorporate open storage filled with toys, art supplies, and books arranged in a visually rich yet organized way. Add a gallery wall featuring children's art and colorful decor. Include varied textures and materials to stimulate creativity. Ensure the room feels lively, inspiring, and full of personality while maintaining structure and balance.",
  },
  hallway: {
    coastal: "Transform this space into a coastal calm hallway interior. Use light oak or whitewashed wood flooring with soft white walls and sandy beige tones, accented with subtle ocean blue details. If present, include a staircase with light wood steps and a white railing, or keep it as a long, open, airy corridor. Incorporate natural textures such as rattan, woven elements, and linen details. Add minimal coastal decor like ceramic vases and soft, neutral artwork. Ensure the space feels bright, open, and uncluttered with strong natural daylight and soft shadows. Style should be clean, relaxed, and airy with a calm beach-house atmosphere. Photorealistic interior photography, wide-angle view (24mm lens), natural lighting, soft depth of field, high detail.",
    modernluxury: "A modern luxury hallway with a sleek and minimalist design, maintaining a clean, high-end aesthetic. The space features smooth walls with subtle paneling or textured finishes, complemented by elegant lighting such as recessed ceiling lights, soft LED strip accents, and refined wall sconces. Flooring is polished marble, natural stone, or high-end wood with a glossy or satin finish. If the original image includes a staircase, transform it into a modern luxury feature with floating steps or refined solid treads, paired with frameless glass banisters or glass railings with minimal metal accents, creating a sophisticated, open, and airy architectural statement. If no staircase is present, maintain a clean corridor layout with uninterrupted lines and balanced proportions. Decorative elements are minimal and curated, such as a statement mirror, slim console table, or large-scale modern artwork. Highly realistic, photorealistic rendering, sharp details, balanced lighting.",
    japandi: "Transform this hallway into a Japandi-style space. Use a clean, minimal design with neutral tones and natural wood accents. Add a simple bench or console table with clean lines. Keep decor sparse—perhaps a single ceramic piece or a small plant. Use soft, warm, diffused lighting to create a calm and welcoming transition space. If the hallway includes a staircase, redesign it in Japandi style with light wood steps and minimal glass banisters or railings for an airy, modern look. Keep the structure simple and elegant, avoiding heavy or ornate details. If no staircase is present, maintain an open, uncluttered flow with emphasis on space, light, and natural materials.",
    scandinavian: "Transform this hallway or stairway into a Scandinavian interior design style. Use white or soft neutral walls combined with light wood flooring. Keep the design minimal with clean lines and very limited furniture, such as a simple bench or coat hooks. Add subtle decor like a mirror or a small plant. Ensure the space feels bright, open, and uncluttered with strong natural or soft artificial lighting. Avoid heavy decoration or dark tones.",
    modernfarmhouse: "A modern farmhouse hallway or stairway with white or shiplap walls and light wood flooring. A staircase may feature wooden steps with black metal balusters or railing for contrast. A slim console table in natural wood is styled with minimal decor such as ceramic vases, greenery, or a mirror. Lighting includes simple black or rustic fixtures. The space is clean, bright, and cohesive, with subtle rustic touches and a welcoming flow.",
    urbanmasculine: "Transform this hallway (and stairway if present) into an Urban Masculine (Modern Industrial Luxe) style. Use a dark palette with charcoal walls, black accents, and warm wood flooring. Incorporate industrial materials such as concrete or brick textures and black metal railings if a staircase is present. Add dramatic lighting—wall sconces, recessed lights, or LED strip lighting to highlight architectural features. Keep decor minimal: a few framed artworks, mirrors, or sculptural elements. Emphasize clean lines and strong visual impact. Maintain a sleek, cohesive flow with a refined industrial luxury feel. Photorealistic, cinematic lighting, 4k.",
    biophilic: "Transform this hallway (and stairway if present) into a biophilic interior design style. Add greenery such as potted plants along the corridor, trailing plants, or a vertical garden wall. Use natural wood for flooring, railings, or accents. Enhance natural light to create a bright, open passage. Apply a neutral earthy palette with organic textures. The space should feel like a transitional natural pathway, calm and refreshing.",
    maximalist: "Transform this hallway (and stairway if present) into a maximalist interior design style. Cover walls with bold wallpaper or rich paint colors. Create a dense gallery wall with a mix of artwork, photographs, mirrors, and frames. Add a patterned runner rug and decorative lighting such as wall sconces or pendant fixtures. Incorporate small furniture pieces or consoles styled with books, plants, and decor objects. Ensure the space feels immersive, layered, and visually striking while maintaining flow and cohesion.",
  },
  bathroom: {
    coastal: "Transform this room into a coastal-style bathroom with a clean, spa-like feel. Use white, beige, and soft blue tones with light tiles and natural textures. Include a light wood or white vanity, simple fixtures, and minimal decor such as glass containers, woven baskets, and soft towels. Keep the space bright, fresh, and uncluttered with soft lighting. Subtle coastal touches only. Photorealistic, high detail.",
    modernluxury: "A modern luxury bathroom with a spa-like atmosphere. Features a freestanding bathtub, walk-in glass shower, and a sleek vanity with marble or stone countertops. Fixtures are high-end in brushed gold, chrome, or matte black. The color palette is neutral with soft lighting that enhances relaxation. Materials include polished stone, large-format tiles, and glass surfaces. Minimal decor such as candles or small plants adds elegance. The space feels clean, serene, and indulgent. Ultra-realistic rendering, soft ambient lighting.",
    japandi: "Transform this bathroom into a Japandi-style spa-like retreat. Use natural materials like wood and stone with a neutral palette of white, beige, and grey. Add a simple wooden vanity and minimal fixtures. Keep surfaces clean and uncluttered. Incorporate soft lighting and subtle textures to create a calm, relaxing atmosphere.",
    scandinavian: "Transform this bathroom into a Scandinavian interior design style. Use a clean palette of white, soft gray, and natural tones. Incorporate light wood elements such as a vanity or shelving. Use simple, modern fixtures with minimal detailing. Add soft textures like cotton towels and subtle decor such as candles or small plants. Keep the design clean, spa-like, and uncluttered with a focus on simplicity, brightness, and natural materials.",
    modernfarmhouse: "A modern farmhouse bathroom with a clean, neutral palette of whites and soft grays, accented by natural wood. A white vanity with a simple design is paired with black metal fixtures. The walls may include shiplap or subtle tile textures. A freestanding tub or walk-in shower adds a modern touch, while rustic elements like wooden shelves or framed mirrors provide warmth. Decor includes minimal greenery, soft towels, and ceramic accessories. The lighting is warm and soft, creating a spa-like yet cozy atmosphere.",
    urbanmasculine: "Transform this bathroom into an Urban Masculine (Modern Industrial Luxe) design. Use a dark, moody palette with charcoal tiles, matte black fixtures, and warm wood accents. Incorporate materials such as concrete, stone, or dark marble for walls and countertops. Use a floating vanity in dark wood or black finish. Add a frameless glass shower with black metal framing. Include industrial-style lighting with warm tones for contrast. Keep decor minimal—neatly arranged towels, simple accessories, and clean surfaces. Focus on a sleek, spa-like yet masculine atmosphere. Photorealistic, cinematic lighting, 4k.",
    biophilic: "Transform this bathroom into a biophilic interior design style. Use natural materials such as stone, wood, and textured surfaces. Add humidity-loving plants like ferns or tropical greenery. Incorporate soft, diffused natural light and a spa-like atmosphere. Use earthy tones and organic shapes. The space should feel like a serene natural retreat, similar to a calming spa environment.",
    maximalist: "Transform this bathroom into a maximalist interior design style. Add bold patterned tiles or wallpaper with intricate designs. Incorporate rich colors and contrasting textures such as marble, brass, glass, and wood. Use statement mirrors, decorative lighting, and stylish fixtures in gold or brass finishes. Add plants, artwork, and curated accessories like trays, candles, and containers. Ensure the space feels luxurious, vibrant, and richly layered while still clean and functional.",
  },
};

function getPrompt(roomId: string, style: string): string {
  const baseRoomId = roomId.replace(/\d+$/, "");
  const roomPrompts = ROOM_STYLE_PROMPTS[baseRoomId] || ROOM_STYLE_PROMPTS[roomId];
  const basePrompt = (roomPrompts && roomPrompts[style])
    ? roomPrompts[style]
    : `Redesign this room in a ${style} interior design style. Professional real estate photograph, perfect lighting, wide angle.`;

  const prefix = "IMPORTANT: Perform a bold, dramatic, complete interior redesign of this room. Completely replace all furniture, finishes, colours, and decor with the new style. Do NOT make subtle changes — fully transform the interior. Keep ONLY the room architecture: the exact same walls, ceiling height, windows, doors, floor plan, and room dimensions must be preserved exactly. ";

  const suffix = " The room structure, proportions, window positions, and door positions must remain identical to the original photograph. Apply the new style boldly and completely. Photorealistic, professional interior photography, wide angle, high detail.";

  return prefix + basePrompt + suffix;
}

export const generateRoomImageFn = createServerFn({ method: "POST" })
  .inputValidator((input: { imageDataUri: string; style: string; roomId: string }) => input)
  .handler(async ({ data }) => {
    const { imageDataUri, style, roomId } = data;

    if (!imageDataUri || !style || !roomId) {
      throw new Error("Image data, style and room type are required");
    }

    try {
      const replicate = new Replicate({
        auth: process.env.REPLICATE_API_TOKEN,
      });

      const prompt = getPrompt(roomId, style);

      let prediction = await replicate.predictions.create({
        model: "google/nano-banana",
        input: {
          prompt,
          image_input: [imageDataUri],
        },
      });

      while (prediction.status !== "succeeded" && prediction.status !== "failed") {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        prediction = await replicate.predictions.get(prediction.id);
      }

      if (prediction.status === "failed") {
        throw new Error(`Prediction failed: ${prediction.error}`);
      }

      let generatedUrl = "";
      if (typeof prediction.output === "string" && prediction.output.startsWith("http")) {
        generatedUrl = prediction.output;
      } else if (Array.isArray(prediction.output) && prediction.output.length > 0) {
        generatedUrl = String(prediction.output[0]);
      } else {
        throw new Error(`Unknown output format: ${JSON.stringify(prediction.output)}`);
      }

      return { success: true, generatedImageUrl: generatedUrl };
    } catch (error) {
      console.error("AI Generation failed:", error);
      return {
        success: false,
        generatedImageUrl: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1024&auto=format&fit=crop",
        warning: `AI generation failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  });
