import { createServerFn } from "@tanstack/react-start";
import Replicate from "replicate";

// Prompt lookup table: ROOM_STYLE_PROMPTS[roomId][styleId]
// Room IDs: kitchen, livingroom, bedroom, kidsroom, playroom, hallway,
//           openplankitchendiner, openplanlounge, diningroom, bathroom, office
// Style IDs: japandi, scandinavian, coastal, urbanmasculine, modernluxury,
//            whites, biophilic, modernfarmhouse, maximalist, minimalist

const ROOM_STYLE_PROMPTS: Record<string, Record<string, string>> = {
  kitchen: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Japandi aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Scandanavian aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Coastal aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Urban Masculine aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Redecorate the decor in this room and Maintain the exact existing architectural layout, room dimensions, window placement, door positions, ceiling height, and all structural elements of the original image, without altering the shape or proportions of the space. Redesign the furnishings in this kitchen with a warm, neutral colour palette dominated by soft beiges, creams, and light stone tones. Matte black accents are used throughout, providing a modern edge against the softer finishes. Countertops should be white natural stone or quartz surfaces, contemprorary mocha coloured cabinetry, and beige marble flooring with LED lighting under cabinets on floors. Decor is minimal, with simple ceramic pieces, bowls, and vessels in muted tones. If any soft furnishings are present they should be cream boucle material and contemporary design. Any plumbing should be matt black. Ceiling light should be modern contemporary and switched on. All walls should be off white. There shoudl be no orange or light wood present in the kitchen. If there is space, add a kitchen island with boucle chairs. If the kitchen is small, do not add an island. any old wood or brick elements should be replaced with clean cream tones.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Whites aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Biophillic aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Modern Farmhouse aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Maximalist aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kitchen into a Minimalist aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  livingroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Japandi aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Scandanavian aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Coastal aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Urban Masculine aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Redecorate the decor in this room and Maintain the exact existing architectural layout, room dimensions, window placement, door positions, ceiling height, and all structural elements of the original image, without altering the shape or proportions of the space. Redesign the furnishings in this living room in a modern contemporary style with warm minimalist influences, creating a calm, neutral, high-end aesthetic. Use a sculptural curved sofa upholstered in cream bouclé fabric, paired with a matching rounded armchair arranged in a balanced, conversational layout. Place a low, contemporary coffee table in a light stone or pale wood finish at the center, positioned on a large textured neutral rug to anchor the seating area. Apply a cohesive palette of warm neutrals, including beige or soft off-white walls, light wood herringbone flooring, and layered soft textiles such as linen, wool, and bouclé. Style living room with minimal decor, a ceramic vase with greenery, and large-scale neutral pallette abstract artwork. Introduce subtle contrast with a dark wood sideboard styled with a modern table lamp and minimal accessories. Include a large round wall mirror. Emphasise soft, rounded furniture, minimal clutter, natural materials, and layered textures, ensuring the space feels balanced. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Whites aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Biophillic aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Modern Farmhouse aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Maximalist aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Living Room into a Minimalist aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  bedroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Japandi aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Scandanavian aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Coastal aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Urban Masculine aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Maintain the exact architectural layout, room dimensions, window placement, door positions, ceiling height, and all structural elements of the original image, without altering the shape or proportions of the space. Redesign the bedroom decor with modern neutral contemporary furnishings. Use a low-profile bed upholstered in soft cream bouclé or textured fabric, styled with layered neutral bedding including crisp white sheets, beige cushions, and a textured throw for added warmth. Place a large woven rug in a natural tone beneath the bed to anchor the space and introduce texture. Use dark wood contemporary bedside tables topped with off white soft, rounded table lamps emitting warm ambient light. Above the bed, position a large piece of abstract artwork in neutral tones. All furniture should be modern contemporary styled with minimal ceramics and decor, use a large round mirror. Include a curved bouclé accent chair. Introduce a potted plant to add a natural, organic element. Emphasise warm neutral tones, soft rounded furniture forms, natural materials such as wood and textiles. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Whites aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Biophillic aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Modern Farmhouse aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Maximalist aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bedroom into a Minimalist aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  kidsroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Japandi aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Scandanavian aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Coastal aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Urban Masculine aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Maintain the exact architectural layout, proportions, window and door placement, and all structural elements of the original image without any alteration. Redesign the room as a child’s bedroom in a modern contemporary, warm minimalist style with subtle Japandi influences, focusing purely on colours, materials, textures, and furnishings. Use a soft, warm neutral palette of creams, beiges, and light wood tones, complemented by gentle pastel accents such as muted sage green, soft blush, or pale sand to create a calm and playful atmosphere. Incorporate natural materials including light wood, soft cottons, wool, and woven textiles to add warmth and tactility. Introduce simple, child-friendly furniture with rounded edges, such as a low bed with soft, neutral bedding and layered cushions for comfort. Add a textured rug in natural tones to create a cozy surface for play. Include minimal, thoughtfully selected decor such as soft toys, simple shelving with books, and ceramic or wooden accessories in muted colours. Integrate subtle greenery or nature-inspired elements to bring an organic feel. Use soft, warm lighting through simple lamps or diffused fixtures to maintain a soothing environment. Emphasise gentle textures, minimal clutter, and a balanced, serene aesthetic that feels both functional and comforting, ensuring the space appears as a high-end, thoughtfully designed child’s room with a calm, modern finish.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Whites aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Biophillic aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Modern Farmhouse aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Maximalist aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Kids Room into a Minimalist aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  playroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Japandi aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Scandanavian aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Coastal aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Urban Masculine aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Luxury Modern aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Modern Luxury aesthetic. Install sleek handleless furniture in cream or grey, add polished marble or quartz surfaces, use brushed brass or gold metallic accents throughout, add layered sophisticated lighting with floor lamps and pendants, incorporate velvet or silk soft furnishings. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Whites aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Biophillic aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Modern Farmhouse aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Maximalist aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Play Room into a Minimalist aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  hallway: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Japandi aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Scandanavian aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Coastal aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Urban Masculine aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Maintain the exact architectural layout, proportions and structural integrity of the room in the original image. Redesign the decor and furnishings using a natural neutral pallette. Change the flooring to beige marble flooring. Change the walls to off white polished stone. add a ceramic vase and light greenery such as an olice plant or eucalyptus. Ceiling light should be matt black contemporary and switched on. Remove any clutter in the room. There should be no wood present in the room. Stairs should have luxurious beige carpet with glass balustrades. All wood or brown elements should be painted cream",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Whites aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Biophillic aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Modern Farmhouse aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Maximalist aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Hallway into a Minimalist aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  openplankitchendiner: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Japandi aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Scandanavian aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Coastal aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Urban Masculine aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Luxury Modern aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Modern Luxury aesthetic. Install sleek handleless furniture in cream or grey, add polished marble or quartz surfaces, use brushed brass or gold metallic accents throughout, add layered sophisticated lighting with floor lamps and pendants, incorporate velvet or silk soft furnishings. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Whites aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Biophillic aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Modern Farmhouse aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Maximalist aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Kitchen/Diner into a Minimalist aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  openplanlounge: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Japandi aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Scandanavian aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Coastal aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Urban Masculine aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Luxury Modern aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Modern Luxury aesthetic. Install sleek handleless furniture in cream or grey, add polished marble or quartz surfaces, use brushed brass or gold metallic accents throughout, add layered sophisticated lighting with floor lamps and pendants, incorporate velvet or silk soft furnishings. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Whites aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Biophillic aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Modern Farmhouse aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Maximalist aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Open Plan Dining Room / Lounge into a Minimalist aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  diningroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Japandi aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Scandanavian aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Coastal aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Urban Masculine aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Maintain the exact architectural layout, proportions, window and door placement, and all structural elements of the original image without any alteration. Redesign the decor in this dining room using warm neutral palette of soft beiges, creams, and light natural tones, contrasted with deeper dark wood elements and subtle matte black accents. Use a dark wood dining table paired with white upholstered chairs in light, in boucle fabric. Use a large pendant light with a simple, sculptural fabric or matte finish. Use a woven cream rug. Use ceramic vases, bowls, and neutral-toned artwork. Use subtle greenery such as an olive plant or eucalyptus.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Whites aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Biophillic aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Modern Farmhouse aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Maximalist aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Dining Room into a Minimalist aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  bathroom: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Japandi aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Scandanavian aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Coastal aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Urban Masculine aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Maintain the exact architectural layout, room dimensions, window placement, door positions, ceiling height, plumbing locations, and all structural elements of the original image, without altering the shape or proportions of the space. Redesign the bathroom furnishings with neutral colours and polished off white ceramic, incorporate matte black fixtures throughout, including wall-mounted taps, shower fittings, and hardware, to introduce contrast against a soft neutral palette. Apply warm, neutral materials across the space, such as beige or soft stone wall finishes and matching floor tiles, to create a cohesive and calming base. Use a large sculptural mirror paired with a modern wall sconce to provide soft, ambient lighting. Add candles and a ceramic vase with greenery. Emphasise warm neutral tones, clean minimal lines, natural materials such as wood, stone, and woven textiles, and a clutter-free, balanced layout. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Whites aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Biophillic aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Modern Farmhouse aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Maximalist aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Bathroom into a Minimalist aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
  office: {
    japandi: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Japandi aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Japandi aesthetic. Install new light oak or walnut furniture, replace all upholstery with linen or cotton in warm whites and beiges, add natural stone or plaster textures, use matte black fixtures and minimal decoration. Serene, calm, and uncluttered. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    scandinavian: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Scandanavian aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Scandinavian design. Paint walls crisp white, install light oak or birch wood furniture, add cozy wool throws and cushions in grey and white, introduce potted green plants and simple pendant lighting. Bright, airy and functional. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    coastal: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Coastal aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Coastal theme. Replace all furniture with light oak and rattan/wicker pieces, add soft furnishings in ocean blue, sandy beige and white, use white marble or stone surfaces, hang sheer white curtains, add coastal accessories like driftwood or sea glass accents. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    urbanmasculine: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Urban Masculine aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Urban Masculine style. Replace all furniture with dark leather, blackened steel and concrete pieces, paint walls in deep charcoal or dark grey, install dark engineered wood flooring, add industrial pendant lighting, use minimal dark accessories. Moody and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernluxury: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Luxury Modern aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Modern Luxury aesthetic. Install sleek handleless furniture in cream or grey, add polished marble or quartz surfaces, use brushed brass or gold metallic accents throughout, add layered sophisticated lighting with floor lamps and pendants, incorporate velvet or silk soft furnishings. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    whites: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Whites aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. All-white aesthetic. Paint everything white or off-white, replace all furniture with white or cream pieces in bouclé, linen and cotton textures, add white marble surfaces, use bleached wood accents, create depth through texture rather than colour. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    biophilic: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Biophillic aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Biophilic design. Fill the room with large indoor plants and hanging greenery, install natural wood and rattan furniture, add stone or terracotta surfaces, use an earthy palette of forest green, terracotta and warm brown, bring the outside in with natural materials throughout. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    modernfarmhouse: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Modern Farmhouse aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Modern Farmhouse style. Install white shaker-style furniture with matte black hardware, add shiplap or board-and-batten wall textures, incorporate reclaimed wood beams or surfaces, use cozy plaid or checked textiles in warm neutrals, add vintage-style lighting fixtures. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    maximalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Maximalist aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Maximalist style. Cover walls with bold patterned wallpaper in emerald or navy, layer multiple rugs, pack the room with eclectic colourful furniture and accessories, add a gallery wall of art, use rich jewel-toned velvet upholstery, mix patterns and textures freely. Bold and dramatic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
    minimalist: "Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this Office into a Minimalist aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Minimalist design. Remove all clutter and decoration, replace furniture with ultra-clean lined pieces in a single neutral tone, hide all storage behind flush doors, use only one or two carefully chosen materials, leave generous empty space. Less is dramatically more. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.",
  },
};

// Map room IDs from tool.tsx to prompt table keys
const ROOM_ID_MAP: Record<string, string> = {
  kitchen: "kitchen",
  livingroom: "livingroom",
  diningroom: "diningroom",
  bedroom: "bedroom",
  kidsroom: "kidsroom",
  playroom: "playroom",
  bathroom: "bathroom",
  hallway: "hallway",
  office: "office",
  openplankitchendiner: "openplankitchendiner",
  openplanlounge: "openplanlounge",
  // Legacy / alternate spellings
  "open-plan-kitchen-diner": "openplankitchendiner",
  "open-plan-lounge": "openplanlounge",
  "open plan kitchen": "openplankitchendiner",
  "open plan lounge": "openplanlounge",
};

// Map style IDs from tool.tsx to prompt table keys
const STYLE_ID_MAP: Record<string, string> = {
  japandi: "japandi",
  scandinavian: "scandinavian",
  coastal: "coastal",
  urbanmasculine: "urbanmasculine",
  modernluxury: "modernluxury",
  whites: "whites",
  biophilic: "biophilic",
  modernfarmhouse: "modernfarmhouse",
  maximalist: "maximalist",
  minimalist: "minimalist",
  // Legacy IDs from old tool.tsx styles
  modernLuxury: "modernluxury",
  "modern luxury": "modernluxury",
  "modern farmhouse": "modernfarmhouse",
  "urban masculine": "urbanmasculine",
};

function getPrompt(roomId: string, style: string): string {
  const normalizedRoom = ROOM_ID_MAP[roomId] || ROOM_ID_MAP[roomId.toLowerCase().replace(/\s+/g, "")] || roomId;
  const normalizedStyle = STYLE_ID_MAP[style] || STYLE_ID_MAP[style.toLowerCase().replace(/\s+/g, "")] || style;

  const roomPrompts = ROOM_STYLE_PROMPTS[normalizedRoom];
  if (roomPrompts && roomPrompts[normalizedStyle]) {
    return roomPrompts[normalizedStyle];
  }

  // Fallback if combination not found
  return `Keep the room's architecture, windows, doors and structural walls exactly as they are. Completely replace ALL existing furniture, soft furnishings, flooring, wall colours, and decorative items. Restyle this ${roomId} into a ${style} aesthetic. Make the transformation dramatic and clearly visible. Photorealistic, high detail, professional interior photography.`;
}

export const generateRoomImageFn = createServerFn({ method: "POST" })
  .inputValidator((input: { imageDataUri: string; style: string; roomId: string }) => input)
  .handler(async ({ data }) => {
    const { imageDataUri, style, roomId } = data;

    if (!imageDataUri || !style || !roomId) {
      throw new Error("Image data, style and room type are required");
    }

    try {
      const replicate = new Replicate({
        auth: process.env.REPLICATE_API_TOKEN,
      });

      const prompt = getPrompt(roomId, style);

      let prediction = await replicate.predictions.create({
        model: "google/nano-banana",
        input: {
          prompt,
          image_input: [imageDataUri],
        },
      });

      while (prediction.status !== "succeeded" && prediction.status !== "failed") {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        prediction = await replicate.predictions.get(prediction.id);
      }

      if (prediction.status === "failed") {
        throw new Error(`Prediction failed: ${prediction.error}`);
      }

      let generatedUrl = "";
      if (typeof prediction.output === "string" && prediction.output.startsWith("http")) {
        generatedUrl = prediction.output;
      } else if (Array.isArray(prediction.output) && prediction.output.length > 0) {
        generatedUrl = String(prediction.output[0]);
      } else {
        throw new Error(`Unknown output format: ${JSON.stringify(prediction.output)}`);
      }

      return { success: true, generatedImageUrl: generatedUrl };
    } catch (error) {
      console.error("AI Generation failed:", error);
      return {
        success: false,
        generatedImageUrl: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1024&auto=format&fit=crop",
        warning: `AI generation failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  });
