import { createServerFn } from "@tanstack/react-start";
import Replicate from "replicate";

// Prompt lookup table: ROOM_STYLE_PROMPTS[roomId][styleId]
// Room IDs: kitchen, livingroom, bedroom, kidsroom, playroom, hallway,
//           openplankitchendiner, openplanlounge, diningroom, bathroom, office
// Style IDs: japandi, scandinavian, coastal, urbanmasculine, modernluxury,
//            whites, biophilic, modernfarmhouse, maximalist, minimalist

const ROOM_STYLE_PROMPTS: Record<string, Record<string, string>> = {
  kitchen: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Japandi aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Scandanavian aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Coastal aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Urban Masculine aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Luxury Modern aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Whites aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Biophillic aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Modern Farmhouse aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Maximalist aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kitchen into a Minimalist aesthetic. Update the cabinetry, countertops, backsplash, and appliances within the current footprint. Replace bar stools or lighting fixtures. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  livingroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Japandi aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Scandanavian aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Coastal aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Urban Masculine aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Luxury Modern aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Whites aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Biophillic aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Modern Farmhouse aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Maximalist aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Living Room into a Minimalist aesthetic. Update the sofa, coffee table, armchairs, and area rug. Refinish walls and flooring. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  bedroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Japandi aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Scandanavian aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Coastal aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Urban Masculine aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Luxury Modern aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Whites aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Biophillic aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Modern Farmhouse aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Maximalist aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bedroom into a Minimalist aesthetic. Update the bed frame, headboard, nightstands, and bedding. Refinish walls and flooring. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  kidsroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Japandi aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Scandanavian aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Coastal aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Urban Masculine aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Luxury Modern aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Whites aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Biophillic aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Modern Farmhouse aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Maximalist aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Kids Room into a Minimalist aesthetic. Update the child-friendly furniture, storage, and playful decor items. Use soft, safe textures. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  playroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Japandi aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Scandanavian aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Coastal aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Urban Masculine aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Luxury Modern aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Whites aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Biophillic aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Modern Farmhouse aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Maximalist aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Play Room into a Minimalist aesthetic. Update the storage units, activity tables, and rugs. Focus on organized, creative zones. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  hallway: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Japandi aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Scandanavian aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Coastal aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Urban Masculine aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Luxury Modern aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Whites aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Biophillic aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Modern Farmhouse aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Maximalist aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Hallway into a Minimalist aesthetic. Refinish flooring and walls. Update console tables, mirrors, or lighting. Maintain staircase structure if present. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  openplankitchendiner: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Japandi aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Scandanavian aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Coastal aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Urban Masculine aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Luxury Modern aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Whites aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Biophillic aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Modern Farmhouse aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Maximalist aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Kitchen/Diner into a Minimalist aesthetic. Maintain a cohesive flow between the kitchen area and dining area. Update cabinetry and the dining set to match. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  openplanlounge: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Japandi aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Scandanavian aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Coastal aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Urban Masculine aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Luxury Modern aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Whites aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Biophillic aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Modern Farmhouse aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Maximalist aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Open Plan Dining Room / Lounge into a Minimalist aesthetic. Maintain a cohesive flow between the dining and lounge zones. Coordinate the dining set with the sofa and rug. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  diningroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Japandi aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Scandanavian aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Coastal aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Urban Masculine aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Luxury Modern aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Whites aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Biophillic aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Modern Farmhouse aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Maximalist aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Dining Room into a Minimalist aesthetic. Update the dining table, chairs, and statement lighting. Add a centerpiece and rug. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  bathroom: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Japandi aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Scandanavian aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Coastal aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Urban Masculine aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Luxury Modern aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Whites aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Biophillic aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Modern Farmhouse aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Maximalist aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Bathroom into a Minimalist aesthetic. Update the vanity, mirror, tiles, and fixtures. Maintain the position of the tub and shower. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
  office: {
    japandi: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Japandi aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Japandi aesthetic. Use light wood, a neutral palette of warm white and beige, natural stone textures, and matte black fixtures. Keep it minimalist and serene with linen textures. Photorealistic, high detail.",
    scandinavian: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Scandanavian aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Scandinavian design. Focus on a bright, clean aesthetic with white walls, light wood (oak or birch) elements, cozy wool textures, and green plants. Minimalist and functional. Photorealistic, high detail.",
    coastal: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Coastal aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Coastal theme. Use a palette of soft whites, warm beige, and muted ocean blues. Incorporate light oak, white marble, wicker textures, and airy linen. Photorealistic, high detail.",
    urbanmasculine: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Urban Masculine aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Urban Masculine style. Use a dark, moody palette with matte black, charcoal, and deep wood tones. Incorporate industrial materials like concrete, leather, and blackened steel. Photorealistic, high detail.",
    modernluxury: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Luxury Modern aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Modern Luxury aesthetic. Features sleek handleless surfaces, polished marble or quartz, metallic accents (brushed brass), and sophisticated layered lighting. Photorealistic, high detail.",
    whites: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Whites aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. All-white aesthetic. Use a layered palette of whites (cream, ivory, stark white). Focus on textures like bouclé, white marble, and light bleached wood for depth. Photorealistic, high detail.",
    biophilic: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Biophillic aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Biophilic design. Incorporate abundant indoor plants, natural wood textures, stone surfaces, and an earthy green and brown palette to connect with nature. Photorealistic, high detail.",
    modernfarmhouse: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Modern Farmhouse aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Modern Farmhouse style. Use white shaker cabinets, matte black hardware, shiplap textures, reclaimed wood, and cozy rustic textiles. Photorealistic, high detail.",
    maximalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Maximalist aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Maximalist style. Use bold jewel tones (emerald, navy), patterned wallpapers, layered rugs, eclectic decor, and gallery walls. Rich and vibrant. Photorealistic, high detail.",
    minimalist: "Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this Office into a Minimalist aesthetic. Update the desk, ergonomic chair, shelving, and task lighting. Focus on a productive, clean environment. Minimalist design. Ultra-clean lines, monochromatic palette, hidden storage, and zero clutter. Focus on the beauty of the materials and architecture. Photorealistic, high detail.",
  },
};

// Map room IDs from tool.tsx to prompt table keys
const ROOM_ID_MAP: Record<string, string> = {
  kitchen: "kitchen",
  livingroom: "livingroom",
  diningroom: "diningroom",
  bedroom: "bedroom",
  kidsroom: "kidsroom",
  playroom: "playroom",
  bathroom: "bathroom",
  hallway: "hallway",
  office: "office",
  openplankitchendiner: "openplankitchendiner",
  openplanlounge: "openplanlounge",
  // Legacy / alternate spellings
  "open-plan-kitchen-diner": "openplankitchendiner",
  "open-plan-lounge": "openplanlounge",
  "open plan kitchen": "openplankitchendiner",
  "open plan lounge": "openplanlounge",
};

// Map style IDs from tool.tsx to prompt table keys
const STYLE_ID_MAP: Record<string, string> = {
  japandi: "japandi",
  scandinavian: "scandinavian",
  coastal: "coastal",
  urbanmasculine: "urbanmasculine",
  modernluxury: "modernluxury",
  whites: "whites",
  biophilic: "biophilic",
  modernfarmhouse: "modernfarmhouse",
  maximalist: "maximalist",
  minimalist: "minimalist",
  // Legacy IDs from old tool.tsx styles
  modernLuxury: "modernluxury",
  "modern luxury": "modernluxury",
  "modern farmhouse": "modernfarmhouse",
  "urban masculine": "urbanmasculine",
};

function getPrompt(roomId: string, style: string): string {
  const normalizedRoom = ROOM_ID_MAP[roomId] || ROOM_ID_MAP[roomId.toLowerCase().replace(/\s+/g, "")] || roomId;
  const normalizedStyle = STYLE_ID_MAP[style] || STYLE_ID_MAP[style.toLowerCase().replace(/\s+/g, "")] || style;

  const roomPrompts = ROOM_STYLE_PROMPTS[normalizedRoom];
  if (roomPrompts && roomPrompts[normalizedStyle]) {
    return roomPrompts[normalizedStyle];
  }

  // Fallback if combination not found
  return `Maintain the exact architectural layout, window placement, door positions, and structural walls of the original image. Change only the surface materials, furniture, and decor. Restyle this ${roomId} into a ${style} aesthetic. Photorealistic, high detail.`;
}

export const generateRoomImageFn = createServerFn({ method: "POST" })
  .inputValidator((input: { imageDataUri: string; style: string; roomId: string }) => input)
  .handler(async ({ data }) => {
    const { imageDataUri, style, roomId } = data;

    if (!imageDataUri || !style || !roomId) {
      throw new Error("Image data, style and room type are required");
    }

    try {
      const replicate = new Replicate({
        auth: process.env.REPLICATE_API_TOKEN,
      });

      const prompt = getPrompt(roomId, style);

      let prediction = await replicate.predictions.create({
        model: "google/nano-banana",
        input: {
          prompt,
          image_input: [imageDataUri],
        },
      });

      while (prediction.status !== "succeeded" && prediction.status !== "failed") {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        prediction = await replicate.predictions.get(prediction.id);
      }

      if (prediction.status === "failed") {
        throw new Error(`Prediction failed: ${prediction.error}`);
      }

      let generatedUrl = "";
      if (typeof prediction.output === "string" && prediction.output.startsWith("http")) {
        generatedUrl = prediction.output;
      } else if (Array.isArray(prediction.output) && prediction.output.length > 0) {
        generatedUrl = String(prediction.output[0]);
      } else {
        throw new Error(`Unknown output format: ${JSON.stringify(prediction.output)}`);
      }

      return { success: true, generatedImageUrl: generatedUrl };
    } catch (error) {
      console.error("AI Generation failed:", error);
      return {
        success: false,
        generatedImageUrl: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1024&auto=format&fit=crop",
        warning: `AI generation failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  });
