/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyDesignsRouteImport } from './routes/my-designs'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EstateAgentToolRouteImport } from './routes/estate-agent-tool'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckoutSuccessRouteImport } from './routes/checout-success'
import { Route as BuyerDashboardRouteImport } from './routes/buyer-dashboard'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDesignsRoute = MyDesignsRouteImport.update({
  id: '/my-designs',
  path: '/my-designs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateAgentToolRoute = EstateAgentToolRouteImport.update({
  id: '/estate-agent-tool',
  path: '/estate-agent-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checout-success',
  path: '/checout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer-dashboard',
  path: '/buyer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/checout-success': typeof CheckoutSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/estate-agent-tool': typeof EstateAgentToolRoute
  '/faq': typeof FaqRoute
  '/my-account': typeof MyAccountRoute
  '/my-designs': typeof MyDesignsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/checout-success': typeof CheckoutSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/estate-agent-tool': typeof EstateAgentToolRoute
  '/faq': typeof FaqRoute
  '/my-account': typeof MyAccountRoute
  '/my-designs': typeof MyDesignsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/checout-success': typeof CheckoutSuccessRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/estate-agent-tool': typeof EstateAgentToolRoute
  '/faq': typeof FaqRoute
  '/my-account': typeof MyAccountRoute
  '/my-designs': typeof MyDesignsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-dashboard' | '/buyer-dashboard' | '/checout-success' | '/checkout' | '/dashboard' | '/estate-agent-tool' | '/faq' | '/my-account' | '/my-designs' | '/sign-in' | '/sign-up' | '/tool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-dashboard' | '/buyer-dashboard' | '/checout-success' | '/checkout' | '/dashboard' | '/estate-agent-tool' | '/faq' | '/my-account' | '/my-designs' | '/sign-in' | '/sign-up' | '/tool'
  id: '__root__' | '/' | '/agent-dashboard' | '/buyer-dashboard' | '/checout-success' | '/checkout' | '/dashboard' | '/estate-agent-tool' | '/faq' | '/my-account' | '/my-designs' | '/sign-in' | '/sign-up' | '/tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  EstateAgentToolRoute: typeof EstateAgentToolRoute
  FaqRoute: typeof FaqRoute
  MyAccountRoute: typeof MyAccountRoute
  MyDesignsRoute: typeof MyDesignsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ToolRoute: typeof ToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-designs': {
      id: '/my-designs'
      path: '/my-designs'
      fullPath: '/my-designs'
      preLoaderRoute: typeof MyDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate-agent-tool': {
      id: '/estate-agent-tool'
      path: '/estate-agent-tool'
      fullPath: '/estate-agent-tool'
      preLoaderRoute: typeof EstateAgentToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checout-success': {
      id: '/checout-success'
      path: '/checout-success'
      fullPath: '/checout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-dashboard': {
      id: '/buyer-dashboard'
      path: '/buyer-dashboard'
      fullPath: '/buyer-dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  EstateAgentToolRoute: EstateAgentToolRoute,
  FaqRoute: FaqRoute,
  MyAccountRoute: MyAccountRoute,
  MyDesignsRoute: MyDesignsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ToolRoute: ToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
