/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmbedDemoRouteImport } from './routes/embed-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDemoRoute = EmbedDemoRouteImport.update({
  id: '/embed-demo',
  path: '/embed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/tool': typeof ToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/embed-demo' | '/faq' | '/tool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/embed-demo' | '/faq' | '/tool'
  id: '__root__' | '/' | '/dashboard' | '/embed-demo' | '/faq' | '/tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmbedDemoRoute: typeof EmbedDemoRoute
  FaqRoute: typeof FaqRoute
  ToolRoute: typeof ToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-demo': {
      id: '/embed-demo'
      path: '/embed-demo'
      fullPath: '/embed-demo'
      preLoaderRoute: typeof EmbedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmbedDemoRoute: EmbedDemoRoute,
  FaqRoute: FaqRoute,
  ToolRoute: ToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
