/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolRouteImport } from './routes/tool'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmbedDemoRouteImport } from './routes/embed-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuyerDashboardRouteImport } from './routes/buyer-dashboard'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const ToolRoute = ToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDemoRoute = EmbedDemoRouteImport.update({
  id: '/embed-demo',
  path: '/embed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer-dashboard',
  path: '/buyer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/buyer-dashboard': typeof BuyerDashboardRoute
  '/dashboard': typeof DashboardRoute
  '/embed-demo': typeof EmbedDemoRoute
  '/faq': typeof FaqRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tool': typeof ToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-dashboard' | '/buyer-dashboard' | '/dashboard' | '/embed-demo' | '/faq' | '/sign-in' | '/sign-up' | '/tool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-dashboard' | '/buyer-dashboard' | '/dashboard' | '/embed-demo' | '/faq' | '/sign-in' | '/sign-up' | '/tool'
  id: '__root__' | '/' | '/agent-dashboard' | '/buyer-dashboard' | '/dashboard' | '/embed-demo' | '/faq' | '/sign-in' | '/sign-up' | '/tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  DashboardRoute: typeof DashboardRoute
  EmbedDemoRoute: typeof EmbedDemoRoute
  FaqRoute: typeof FaqRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ToolRoute: typeof ToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tool': {
      id: '/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof ToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-demo': {
      id: '/embed-demo'
      path: '/embed-demo'
      fullPath: '/embed-demo'
      preLoaderRoute: typeof EmbedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-dashboard': {
      id: '/buyer-dashboard'
      path: '/buyer-dashboard'
      fullPath: '/buyer-dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  DashboardRoute: DashboardRoute,
  EmbedDemoRoute: EmbedDemoRoute,
  FaqRoute: FaqRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ToolRoute: ToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
